# Generated by Django 4.0.6 on 2022-07-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('independent', models.BooleanField()),
                ('description', models.TextField(max_length=3000)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('inProgress', models.BooleanField()),
                ('img', models.ImageField(upload_to='uploads')),
                ('link', models.CharField(max_length=500)),
                ('association', models.ManyToManyField(to='sevanbnet.association')),
                ('topic', models.ManyToManyField(to='sevanbnet.topic')),
            ],
            options={
                'ordering': ['inProgress', '-end', 'title'],
            },
        ),
    ]
