# Generated by Django 4.0.6 on 2022-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['ongoing', '-end', 'title']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='inProgress',
            new_name='ongoing',
        ),
        migrations.AlterField(
            model_name='project',
            name='association',
            field=models.ManyToManyField(blank=True, to='sevanbnet.association'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='topic',
            field=models.ManyToManyField(blank=True, to='sevanbnet.topic'),
        ),
    ]
