# Generated by Django 4.0.6 on 2022-07-11 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0003_alter_project_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
