# Generated by Django 4.0.6 on 2022-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0004_alter_project_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
