# Generated by Django 4.0.6 on 2022-07-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0005_alter_project_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
