# Generated by Django 4.2.3 on 2023-11-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0011_alter_blogpost_options_alter_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.TextField()),
                ('association', models.ManyToManyField(blank=True, to='sevanbnet.association')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('journal_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('citation', models.TextField(blank=True)),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('submission_date', models.DateTimeField(blank=True)),
                ('publication_date', models.DateTimeField(blank=True)),
                ('first_author', models.BooleanField()),
                ('association', models.ManyToManyField(blank=True, to='sevanbnet.association')),
                ('authors', models.ManyToManyField(blank=True, to='sevanbnet.author')),
                ('topic', models.ManyToManyField(blank=True, to='sevanbnet.topic')),
            ],
            options={
                'ordering': ['-publication_date', '-submission_date'],
            },
        ),
    ]
