# Generated by Django 4.2.3 on 2023-11-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0012_author_alter_blogpost_published_date_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
