# Generated by Django 4.2.3 on 2024-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sevanbnet", "0021_alter_publication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
