# Generated by Django 4.2.3 on 2024-05-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sevanbnet", "0022_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
