# Generated by Django 4.2.3 on 2024-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sevanbnet", "0024_alter_project_options_remove_blogpost_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": [
                    models.Case(
                        models.When(end__isnull=True, then=models.Value(0)),
                        default=models.Value(1),
                        output_field=models.IntegerField(),
                    ),
                    "-end",
                    "title",
                ]
            },
        ),
    ]
