# Generated by Django 4.2.3 on 2026-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevanbnet", "0026_qrredirect_scan"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrredirect",
            name="bg_transparent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="qrredirect",
            name="qr_radius",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="qrredirect",
            name="qr_style",
            field=models.CharField(
                choices=[
                    ("square", "Square"),
                    ("rounded", "Rounded"),
                    ("circle", "Circle"),
                    ("gapped", "Gapped"),
                ],
                default="square",
                max_length=10,
            ),
        ),
    ]
