# Generated by Django 4.2.3 on 2026-05-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0027_qrredirect_bg_transparent_qrredirect_qr_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='site_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
