# Generated by Django 4.2.3 on 2026-05-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0028_publication_site_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
