# Generated by Django 4.2.3 on 2026-05-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevanbnet', '0029_publication_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='project_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
