# Generated by Django 4.2.3 on 2023-11-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_author_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date', '-submission_date', 'title']},
        ),
    ]
