# Generated by Django 4.2.3 on 2023-12-14 04:44
from django.utils.text import slugify
from django.db import migrations, models

def populate_slugs(apps, schema_editor):
    BlogPost = apps.get_model('your_app_name', 'BlogPost')
    for post in BlogPost.objects.all():
        post.slug = slugify(post.title) or 'default-slug'
        post.save()

class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_blogpost_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
