# Generated by Django 4.2.3 on 2023-12-14 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0021_alter_blogpost_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="slug",
        ),
    ]
